name: ci

on:
  # run tests on push events
  push:
  # run tests on PR events
  pull_request:
    types: [opened, synchronize]

  workflow_dispatch:


jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
        fail-fast: false
        matrix:
            os: [ubuntu-20.04,macos-12]
            #branch: [BRANCH_1,BRANCH_2]

    steps:
      - uses: actions/checkout@v4
        with:
          path: hello-world

      - name: compilation
        if: matrix.os == 'ubuntu-20.04'
        run: |
          #gcc -D ${{ matrix.branch }} -O0 -fprofile-arcs -ftest-coverage hello-world/hello-world.c
          gcc -D BRANCH_1 -O0 -fprofile-arcs -ftest-coverage hello-world/hello-world.c

      - name: compilation
        if: matrix.os != 'ubuntu-20.04'
        run: |
          gcc -D  BRANCH_2 -O0 -fprofile-arcs -ftest-coverage hello-world/hello-world.c


      - name: exec
        run: |
          ./a.out 2 1

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          fail_ci_if_error: true
          root_dir: .
          verbose: true
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
